/**
 * DriveEasy – Complete Car Inventory Dataset
 * Contains 102 distinct car models commonly available across India.
 * Features verified, high-resolution automotive imagery per car company and model.
 */

const CARS_DATA = [
  {
    "id": 1,
    "brand": "Tata",
    "model": "Nano",
    "fullName": "Tata Nano GenX",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 4,
    "dailyRate": 850,
    "perKmRate": 7,
    "driverDailyRate": 600,
    "image": "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata nano genx",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1001",
    "year": 2023,
    "description": "Compact city hatchback, ideal for tight parking, short urban commutes and budget friendly city trips."
  },
  {
    "id": 2,
    "brand": "Tata",
    "model": "Tiago",
    "fullName": "Tata Tiago XZ+",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 5,
    "dailyRate": 1100,
    "perKmRate": 8,
    "driverDailyRate": 650,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata tiago",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1002",
    "year": 2024,
    "description": "Safe 4-star GNCAP rated family hatchback with great driving dynamics, Harman sound and comfortable seating."
  },
  {
    "id": 3,
    "brand": "Tata",
    "model": "Tigor",
    "fullName": "Tata Tigor XZ+",
    "type": "Sedan",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 5,
    "dailyRate": 1250,
    "perKmRate": 8.5,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata tigor",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 39 DE 1003",
    "year": 2023,
    "description": "Compact sedan with spacious 419-litre boot space, digital cluster, and superior structural rigidity."
  },
  {
    "id": 4,
    "brand": "Tata",
    "model": "Altroz",
    "fullName": "Tata Altroz Racer",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 5,
    "dailyRate": 1350,
    "perKmRate": 9,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata altroz",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 04 DE 1004",
    "year": 2024,
    "description": "Premium gold-standard 5-star GNCAP hatchback with 90-degree opening doors and laser-welded roof."
  },
  {
    "id": 5,
    "brand": "Tata",
    "model": "Punch",
    "fullName": "Tata Punch Creative",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 5,
    "dailyRate": 1450,
    "perKmRate": 9,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata punch",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 12 DE 1005",
    "year": 2024,
    "description": "Sub-compact micro-SUV with 187mm ground clearance, commanding seating position, and rugged build."
  },
  {
    "id": 6,
    "brand": "Tata",
    "model": "Nexon",
    "fullName": "Tata Nexon Fearless+",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1750,
    "perKmRate": 10,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata nexon facelift",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 01 DE 1006",
    "year": 2024,
    "description": "India's highest rated safety SUV with 360-degree camera, ventilated seats, and paddle shifters."
  },
  {
    "id": 7,
    "brand": "Tata",
    "model": "Curvv",
    "fullName": "Tata Curvv Accomplished+",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2150,
    "perKmRate": 11,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata curvv",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TN 07 DE 1007",
    "year": 2025,
    "description": "Futuristic coupe-SUV with aerodynamic silhouette, flush door handles, and level-2 ADAS suite."
  },
  {
    "id": 8,
    "brand": "Tata",
    "model": "Harrier",
    "fullName": "Tata Harrier Dark Edition",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2500,
    "perKmRate": 13,
    "driverDailyRate": 900,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata harrier facelift",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1008",
    "year": 2024,
    "description": "Land Rover D8 platform inspired flagship 5-seater with Kryotec 170PS diesel engine and panoramic sunroof."
  },
  {
    "id": 9,
    "brand": "Tata",
    "model": "Safari",
    "fullName": "Tata Safari Accomplished 7-Seater",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 2800,
    "perKmRate": 14,
    "driverDailyRate": 950,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata safari facelift",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 07 DE 1009",
    "year": 2024,
    "description": "Legendary 7-seater highway cruiser with boss mode passenger seat, ambient mood lighting and terrain modes."
  },
  {
    "id": 10,
    "brand": "Tata",
    "model": "Tiago EV",
    "fullName": "Tata Tiago EV Long Range",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1400,
    "perKmRate": 6.5,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata tiago ev",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 39 DE 1010",
    "year": 2024,
    "description": "Zero emission, ultra quiet electric hatchback with 315km range and multi-mode regenerative braking."
  },
  {
    "id": 11,
    "brand": "Tata",
    "model": "Punch EV",
    "fullName": "Tata Punch EV Empowered",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1650,
    "perKmRate": 7,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata punch ev",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 01 DE 1011",
    "year": 2024,
    "description": "Acti.EV platform based all-electric micro SUV with 421km certified range and front charging port."
  },
  {
    "id": 12,
    "brand": "Tata",
    "model": "Nexon EV",
    "fullName": "Tata Nexon EV Max Empowered+",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1950,
    "perKmRate": 7.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata nexon ev",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "KA 03 DE 1012",
    "year": 2024,
    "description": "India's bestselling electric SUV featuring 465km range, V2L vehicle-to-load charging, and 12.3-inch screen."
  },
  {
    "id": 13,
    "brand": "Tata",
    "model": "Curvv EV",
    "fullName": "Tata Curvv.ev 55kWh Long Range",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2400,
    "perKmRate": 8,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "tata curvv ev",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1013",
    "year": 2025,
    "description": "585km long range electric coupe SUV with fast charging capability and panoramic sky roof."
  },
  {
    "id": 14,
    "brand": "Maruti Suzuki",
    "model": "Alto K10",
    "fullName": "Maruti Suzuki Alto K10 VXi+",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 4,
    "dailyRate": 900,
    "perKmRate": 7,
    "driverDailyRate": 600,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki alto k10",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1014",
    "year": 2023,
    "description": "Reliable, easy-to-drive city commuter with stellar fuel efficiency and smart infotainment."
  },
  {
    "id": 15,
    "brand": "Maruti Suzuki",
    "model": "S-Presso",
    "fullName": "Maruti Suzuki S-Presso VXi",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 5,
    "dailyRate": 950,
    "perKmRate": 7,
    "driverDailyRate": 600,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki s-presso",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "DL 01 DE 1015",
    "year": 2023,
    "description": "Mini SUV styling with tall boy stance, high ground clearance, and effortless ingress/egress."
  },
  {
    "id": 16,
    "brand": "Maruti Suzuki",
    "model": "Celerio",
    "fullName": "Maruti Suzuki Celerio ZXi",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1050,
    "perKmRate": 7.5,
    "driverDailyRate": 650,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki celerio",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 05 DE 1016",
    "year": 2024,
    "description": "India's most fuel-efficient petrol hatchback with AGS automatic gearbox and 3D organic sculpted design."
  },
  {
    "id": 17,
    "brand": "Maruti Suzuki",
    "model": "Wagon R",
    "fullName": "Maruti Suzuki Wagon R 1.2 ZXi+",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 5,
    "dailyRate": 1100,
    "perKmRate": 8,
    "driverDailyRate": 650,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki wagon r",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 07 DE 1017",
    "year": 2023,
    "description": "The classic tall-boy family car with unmatched headroom, comfortable upright seating, and massive luggage room."
  },
  {
    "id": 18,
    "brand": "Maruti Suzuki",
    "model": "Swift",
    "fullName": "Maruti Suzuki New Swift ZXi+",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 5,
    "dailyRate": 1250,
    "perKmRate": 8.5,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "new maruti swift 2024",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1018",
    "year": 2024,
    "description": "New 4th-gen Swift powered by the Z-Series engine with 6 airbags standard, wireless charging, and sporty dynamics."
  },
  {
    "id": 19,
    "brand": "Maruti Suzuki",
    "model": "Dzire",
    "fullName": "Maruti Suzuki All-New Dzire ZXi+",
    "type": "Sedan",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1400,
    "perKmRate": 8.5,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki dzire",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 02 DE 1019",
    "year": 2025,
    "description": "India's highest rated 5-star GNCAP compact sedan with electric sunroof, 360-degree camera, and refined ride quality."
  },
  {
    "id": 20,
    "brand": "Maruti Suzuki",
    "model": "Baleno",
    "fullName": "Maruti Suzuki Baleno Alpha",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1350,
    "perKmRate": 8.5,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki baleno alpha",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 16 DE 1020",
    "year": 2024,
    "description": "NEXA premium hatchback featuring Heads-Up Display (HUD), 360 view camera, and Arkamys premium surround sound."
  },
  {
    "id": 21,
    "brand": "Maruti Suzuki",
    "model": "Fronx",
    "fullName": "Maruti Suzuki Fronx Turbo Alpha",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1550,
    "perKmRate": 9.5,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki fronx",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 01 DE 1021",
    "year": 2024,
    "description": "Sporty crossover SUV with Boosterjet turbo petrol engine, paddle shifters, and distinctive coupe roofline."
  },
  {
    "id": 22,
    "brand": "Maruti Suzuki",
    "model": "Brezza",
    "fullName": "Maruti Suzuki Brezza ZXi+",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1650,
    "perKmRate": 10,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki brezza zxi",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "DL 03 DE 1022",
    "year": 2024,
    "description": "Bestselling compact SUV with electric sunroof, Smart Hybrid technology, and robust highway manners."
  },
  {
    "id": 23,
    "brand": "Maruti Suzuki",
    "model": "Ertiga",
    "fullName": "Maruti Suzuki Ertiga ZXi AT",
    "type": "MUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 1850,
    "perKmRate": 11,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki ertiga",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 39 DE 1023",
    "year": 2024,
    "description": "Popular 7-seater family MPV with reclining 2nd/3rd row seats, automatic climate control and smooth 6-speed AT."
  },
  {
    "id": 24,
    "brand": "Maruti Suzuki",
    "model": "XL6",
    "fullName": "Maruti Suzuki XL6 Alpha+ 6-Seater",
    "type": "MUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 6,
    "dailyRate": 2000,
    "perKmRate": 11.5,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki xl6",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 08 DE 1024",
    "year": 2024,
    "description": "NEXA 6-seater premium MPV with 2nd row captain chairs, ventilated front seats, and tire pressure monitoring."
  },
  {
    "id": 25,
    "brand": "Maruti Suzuki",
    "model": "Grand Vitara",
    "fullName": "Maruti Suzuki Grand Vitara Strong Hybrid",
    "type": "SUV",
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2200,
    "perKmRate": 11,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki grand vitara",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 14 DE 1025",
    "year": 2024,
    "description": "Mid-size hybrid SUV delivering 27.97 km/l fuel economy with EV mode, panoramic roof, and ALLGRIP capability."
  },
  {
    "id": 26,
    "brand": "Maruti Suzuki",
    "model": "Jimny",
    "fullName": "Maruti Suzuki Jimny Alpha 4x4",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 4,
    "dailyRate": 1900,
    "perKmRate": 11,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki jimny",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1026",
    "year": 2024,
    "description": "Authentic 4x4 off-roader with ladder-frame chassis, rigid 3-link axles, ALLGRIP PRO low range gearbox."
  },
  {
    "id": 27,
    "brand": "Maruti Suzuki",
    "model": "Invicto",
    "fullName": "Maruti Suzuki Invicto Alpha+ 7-Seater",
    "type": "MUV",
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 3100,
    "perKmRate": 15,
    "driverDailyRate": 950,
    "image": "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "maruti suzuki invicto",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 04 DE 1027",
    "year": 2024,
    "description": "Luxury strong hybrid MPV with powered ottoman seats, dual zone climate control and effortless highway comfort."
  },
  {
    "id": 28,
    "brand": "Hyundai",
    "model": "Grand i10 NIOS",
    "fullName": "Hyundai Grand i10 NIOS Asta",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1150,
    "perKmRate": 8,
    "driverDailyRate": 650,
    "image": "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai grand i10 nios",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 21 DE 1028",
    "year": 2024,
    "description": "Youthful city hatchback with 6 airbags standard, cruise control, cooled glovebox, and sleek LED DRLs."
  },
  {
    "id": 29,
    "brand": "Hyundai",
    "model": "i20",
    "fullName": "Hyundai i20 Asta (O)",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 5,
    "dailyRate": 1350,
    "perKmRate": 8.5,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai i20",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "DL 02 DE 1029",
    "year": 2023,
    "description": "Sharp European styled premium hatchback with Bose 7-speaker sound, electric sunroof, and air purifier."
  },
  {
    "id": 30,
    "brand": "Hyundai",
    "model": "i20 N Line",
    "fullName": "Hyundai i20 N Line N8 DCT",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1600,
    "perKmRate": 10,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai i20 n line",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1030",
    "year": 2024,
    "description": "Performance hot hatch with 120PS turbo engine, dual tip exhaust roar, 4 disc brakes, and paddle shifters."
  },
  {
    "id": 31,
    "brand": "Hyundai",
    "model": "Aura",
    "fullName": "Hyundai Aura SX+",
    "type": "Sedan",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1300,
    "perKmRate": 8.5,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai aura",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1031",
    "year": 2023,
    "description": "Compact family sedan with smooth AMT transmission, diamond pattern front grille, and spacious interior."
  },
  {
    "id": 32,
    "brand": "Hyundai",
    "model": "Exter",
    "fullName": "Hyundai Exter SX (O) Connect",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1450,
    "perKmRate": 9,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai exter",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 12 DE 1032",
    "year": 2024,
    "description": "Micro SUV equipped with factory dashcam with dual cameras, voice-enabled smart electric sunroof and 6 airbags."
  },
  {
    "id": 33,
    "brand": "Hyundai",
    "model": "Venue",
    "fullName": "Hyundai Venue SX (O)",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1650,
    "perKmRate": 10,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai venue",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TN 02 DE 1033",
    "year": 2024,
    "description": "Connected compact SUV featuring 2-step reclining rear seats, ambient sounds of nature, and 60+ BlueLink features."
  },
  {
    "id": 34,
    "brand": "Hyundai",
    "model": "Venue N Line",
    "fullName": "Hyundai Venue N Line N8",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1800,
    "perKmRate": 10.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai venue n line",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "KA 01 DE 1034",
    "year": 2024,
    "description": "Sport-tuned suspension, dual exhausts, red design accents, and metal pedals for spirited highway drives."
  },
  {
    "id": 35,
    "brand": "Hyundai",
    "model": "Creta",
    "fullName": "Hyundai New Creta SX (O)",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2000,
    "perKmRate": 11,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai new creta 2024",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 16 DE 1035",
    "year": 2024,
    "description": "India's undisputable favorite mid-size SUV featuring Level-2 ADAS with 19 safety features, panoramic roof, and Bose audio."
  },
  {
    "id": 36,
    "brand": "Hyundai",
    "model": "Creta N Line",
    "fullName": "Hyundai Creta N Line N10 DCT",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2200,
    "perKmRate": 12,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai creta n line",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1036",
    "year": 2024,
    "description": "160PS 1.5 Turbo GDi engine with track-inspired styling, twin-tip muffler, and N-exclusive 18-inch alloys."
  },
  {
    "id": 37,
    "brand": "Hyundai",
    "model": "Creta Electric",
    "fullName": "Hyundai Creta EV Long Range",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2350,
    "perKmRate": 8,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai creta electric",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 01 DE 1037",
    "year": 2025,
    "description": "All electric variant of India's favorite SUV with 480km certified range and silent instant torque delivery."
  },
  {
    "id": 38,
    "brand": "Hyundai",
    "model": "Alcazar",
    "fullName": "Hyundai Alcazar Signature 7-Seater",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 2300,
    "perKmRate": 12,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai alcazar",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 39 DE 1038",
    "year": 2024,
    "description": "Premium 7-seater SUV with dual-curved 10.25 screens, ventilated 1st and 2nd row seats, and 360-degree camera."
  },
  {
    "id": 39,
    "brand": "Hyundai",
    "model": "Verna",
    "fullName": "Hyundai Verna SX (O) Turbo",
    "type": "Sedan",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1900,
    "perKmRate": 10.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai verna 2023",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 04 DE 1039",
    "year": 2024,
    "description": "5-star GNCAP rated executive sedan with 160PS power, seamless horizon LED lightbar, and heated front seats."
  },
  {
    "id": 40,
    "brand": "Hyundai",
    "model": "Tucson",
    "fullName": "Hyundai Tucson Signature AWD",
    "type": "Luxury",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 3400,
    "perKmRate": 17,
    "driverDailyRate": 950,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai tucson signature",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 05 DE 1040",
    "year": 2024,
    "description": "Parametric jewel hidden lighting, HTRAC All-Wheel-Drive, 8-speed automatic and whisper-quiet ride."
  },
  {
    "id": 41,
    "brand": "Hyundai",
    "model": "Ioniq 5",
    "fullName": "Hyundai Ioniq 5 EV AWD",
    "type": "Luxury",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 4800,
    "perKmRate": 18,
    "driverDailyRate": 1200,
    "image": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "hyundai ioniq 5",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 07 DE 1041",
    "year": 2024,
    "description": "World Car of the Year 800V ultra-fast charging electric vehicle with relaxation seats and sliding center console."
  },
  {
    "id": 42,
    "brand": "Mahindra",
    "model": "Bolero",
    "fullName": "Mahindra Bolero B6 (O)",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Manual",
    "seats": 7,
    "dailyRate": 1450,
    "perKmRate": 9.5,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra bolero",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1042",
    "year": 2023,
    "description": "India's tough workhorse SUV built on metal bodywork with mHawk75 diesel power, built for harsh rural and highway roads."
  },
  {
    "id": 43,
    "brand": "Mahindra",
    "model": "Bolero Neo",
    "fullName": "Mahindra Bolero Neo N10 (O)",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Manual",
    "seats": 7,
    "dailyRate": 1600,
    "perKmRate": 10,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra bolero neo",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "TS 09 DE 1043",
    "year": 2024,
    "description": "Modernized rear-wheel drive Bolero with Multi-Terrain Technology (MTT) mechanical locking differential."
  },
  {
    "id": 44,
    "brand": "Mahindra",
    "model": "Scorpio Classic",
    "fullName": "Mahindra Scorpio Classic S11",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Manual",
    "seats": 7,
    "dailyRate": 2100,
    "perKmRate": 12.5,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra scorpio classic",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 01 DE 1044",
    "year": 2024,
    "description": "The iconic muscle SUV featuring Gen-2 mHawk diesel engine with 300Nm torque and commanding road presence."
  },
  {
    "id": 45,
    "brand": "Mahindra",
    "model": "Scorpio-N",
    "fullName": "Mahindra Scorpio-N Z8L 4x4",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 2400,
    "perKmRate": 13.5,
    "driverDailyRate": 900,
    "image": "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra scorpio n",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 12 DE 1045",
    "year": 2024,
    "description": "Big Daddy of SUVs with 5-star safety rating, 4XPLOR terrain management system, and Sony 3D immersive audio."
  },
  {
    "id": 46,
    "brand": "Mahindra",
    "model": "Thar",
    "fullName": "Mahindra Thar LX 4x4 Hard Top",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Manual",
    "seats": 4,
    "dailyRate": 2150,
    "perKmRate": 12.5,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra thar hard top",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 16 DE 1046",
    "year": 2024,
    "description": "India's lifestyle 4x4 icon with shift-on-the-fly 4WD transfer case, water-resistant interior, and removable roof."
  },
  {
    "id": 47,
    "brand": "Mahindra",
    "model": "Thar Roxx",
    "fullName": "Mahindra Thar Roxx AX7L 4x4",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2600,
    "perKmRate": 14,
    "driverDailyRate": 900,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra thar roxx",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1047",
    "year": 2025,
    "description": "5-door Thar with panoramic sunroof, ventilated front seats, Level-2 ADAS, and Harman Kardon acoustics."
  },
  {
    "id": 48,
    "brand": "Mahindra",
    "model": "XUV 3XO",
    "fullName": "Mahindra XUV 3XO AX7L",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1600,
    "perKmRate": 9.5,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra xuv 3xo",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 03 DE 1048",
    "year": 2024,
    "description": "Feature-loaded compact SUV with segment-first skyroof, Level-2 ADAS, electronic parking brake, and 130PS mStallion engine."
  },
  {
    "id": 49,
    "brand": "Mahindra",
    "model": "XUV700",
    "fullName": "Mahindra XUV700 AX7 Luxury AWD",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 2700,
    "perKmRate": 14,
    "driverDailyRate": 900,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra xuv700",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 39 DE 1049",
    "year": 2024,
    "description": "Flagship 7-seater with dual HD superscreens, Sony 12-speaker 3D sound, smart door handles, and 185PS diesel power."
  },
  {
    "id": 50,
    "brand": "Mahindra",
    "model": "XUV400 EV",
    "fullName": "Mahindra XUV400 Pro EL EV",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1900,
    "perKmRate": 7.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra xuv400 ev",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "MH 01 DE 1050",
    "year": 2024,
    "description": "Electrifying 0-100 in 8.3 seconds with 456km range and copper accented dual-tone aerodynamic exterior."
  },
  {
    "id": 51,
    "brand": "Mahindra",
    "model": "BE 6",
    "fullName": "Mahindra BE 6e Electric SUV",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 3200,
    "perKmRate": 12,
    "driverDailyRate": 950,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra be 6e",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 04 DE 1051",
    "year": 2025,
    "description": "Born-electric INGLO platform vehicle with race-inspired cockpit, active aerodynamics, and ultra rapid charging."
  },
  {
    "id": 52,
    "brand": "Mahindra",
    "model": "XEV 9e",
    "fullName": "Mahindra XEV 9e Flagship EV",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 3500,
    "perKmRate": 13,
    "driverDailyRate": 1000,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mahindra xev 9e",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1052",
    "year": 2025,
    "description": "Luxury electric flagship SUV coupe with triple high-definition digital panoramic displays and 550km range."
  },
  {
    "id": 53,
    "brand": "Toyota",
    "model": "Glanza",
    "fullName": "Toyota Glanza V AT",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1250,
    "perKmRate": 8,
    "driverDailyRate": 650,
    "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota glanza",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1053",
    "year": 2024,
    "description": "Toyota's dependable premium hatchback with smart playcast infotainment, 6 airbags, and exceptional fuel economy."
  },
  {
    "id": 54,
    "brand": "Toyota",
    "model": "Urban Cruiser Hyryder",
    "fullName": "Toyota Urban Cruiser Hyryder Hybrid",
    "type": "SUV",
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2100,
    "perKmRate": 10.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota urban cruiser hyryder",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 01 DE 1054",
    "year": 2024,
    "description": "Self-charging hybrid electric SUV with pure EV mode, ventilated front seats, and heads up display."
  },
  {
    "id": 55,
    "brand": "Toyota",
    "model": "Rumion",
    "fullName": "Toyota Rumion V AT 7-Seater",
    "type": "MUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 1950,
    "perKmRate": 11,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota rumion",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "TS 08 DE 1055",
    "year": 2024,
    "description": "Comfortable 7-seater multi-utility family vehicle backed by Toyota's legendary peace of mind and warranty."
  },
  {
    "id": 56,
    "brand": "Toyota",
    "model": "Innova Crysta",
    "fullName": "Toyota Innova Crysta 2.4 VX",
    "type": "MUV",
    "fuel": "Diesel",
    "transmission": "Manual",
    "seats": 7,
    "dailyRate": 2600,
    "perKmRate": 14,
    "driverDailyRate": 900,
    "image": "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota innova crysta",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 16 DE 1056",
    "year": 2024,
    "description": "The gold benchmark for Indian highway touring: indestructible chassis, sofa-like comfort, and bulletproof diesel engine."
  },
  {
    "id": 57,
    "brand": "Toyota",
    "model": "Innova Hycross",
    "fullName": "Toyota Innova Hycross ZX(O) Hybrid",
    "type": "MUV",
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 3100,
    "perKmRate": 14.5,
    "driverDailyRate": 950,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota innova hycross",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 02 DE 1057",
    "year": 2025,
    "description": "Ultra-luxurious hybrid MPV with powered ottoman second-row lounge seats, panoramic roof and Toyota Safety Sense ADAS."
  },
  {
    "id": 58,
    "brand": "Toyota",
    "model": "Fortuner",
    "fullName": "Toyota Fortuner 4x4 AT",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 3800,
    "perKmRate": 18,
    "driverDailyRate": 1000,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota fortuner",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 39 DE 1058",
    "year": 2024,
    "description": "Unrivalled Indian road king with 500Nm torque, high water wading clearance, and unstoppable 4x4 capability."
  },
  {
    "id": 59,
    "brand": "Toyota",
    "model": "Legender",
    "fullName": "Toyota Fortuner Legender 4x4",
    "type": "Luxury",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 4300,
    "perKmRate": 20,
    "driverDailyRate": 1100,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota fortuner legender",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 01 DE 1059",
    "year": 2024,
    "description": "Aggressive Lexus-inspired catamaran styling with sequential turn signals, wireless charging and premium dual-tone interior."
  },
  {
    "id": 60,
    "brand": "Toyota",
    "model": "Hilux",
    "fullName": "Toyota Hilux 4x4 High AT",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 3600,
    "perKmRate": 17,
    "driverDailyRate": 1000,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota hilux",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "KA 05 DE 1060",
    "year": 2024,
    "description": "Globally proven adventure lifestyle pickup truck with 700mm water wading capacity and 4x4 electronic differential lock."
  },
  {
    "id": 61,
    "brand": "Toyota",
    "model": "Camry",
    "fullName": "Toyota Camry Hybrid Luxury Sedan",
    "type": "Luxury",
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 5200,
    "perKmRate": 24,
    "driverDailyRate": 1200,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota camry hybrid",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1061",
    "year": 2024,
    "description": "First-class executive luxury sedan featuring reclining rear electric seats, 9-speaker JBL audio and whisper-quiet hybrid drive."
  },
  {
    "id": 62,
    "brand": "Toyota",
    "model": "Vellfire",
    "fullName": "Toyota Vellfire VIP Executive Lounge",
    "type": "Luxury",
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 8500,
    "perKmRate": 35,
    "driverDailyRate": 1500,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "toyota vellfire",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 01 DE 1062",
    "year": 2025,
    "description": "Private jet on wheels with heated massage captain seats, ceiling screen entertainment, and twin sunroofs."
  },
  {
    "id": 63,
    "brand": "Honda",
    "model": "Amaze",
    "fullName": "Honda All-New Amaze VX CVT",
    "type": "Sedan",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1300,
    "perKmRate": 8.5,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "honda amaze",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 16 DE 1063",
    "year": 2024,
    "description": "Smart family sedan with butter-smooth CVT automatic, paddle shifters, LED projector headlamps and 420L boot space."
  },
  {
    "id": 64,
    "brand": "Honda",
    "model": "City",
    "fullName": "Honda City 5th Gen ZX CVT",
    "type": "Sedan",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1650,
    "perKmRate": 9.5,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "honda city 5th gen",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 03 DE 1064",
    "year": 2024,
    "description": "India's executive sedan benchmark powered by 1.5L i-VTEC engine, Honda Sensing ADAS, and plush leather upholstery."
  },
  {
    "id": 65,
    "brand": "Honda",
    "model": "City e:HEV",
    "fullName": "Honda City Hybrid e:HEV ZX",
    "type": "Sedan",
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2100,
    "perKmRate": 11,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "honda city e hev",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "KA 01 DE 1065",
    "year": 2024,
    "description": "Twin-motor self-charging hybrid sedan delivering 27.13 km/l with electric drive, auto brake hold and lane watch camera."
  },
  {
    "id": 66,
    "brand": "Honda",
    "model": "Elevate",
    "fullName": "Honda Elevate ZX CVT",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1800,
    "perKmRate": 10,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "honda elevate",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1066",
    "year": 2024,
    "description": "Urban Japanese SUV boasting 220mm best-in-segment ground clearance, class-leading 458L boot and Honda Sensing camera ADAS."
  },
  {
    "id": 67,
    "brand": "Kia",
    "model": "Sonet",
    "fullName": "Kia Sonet GTX+ 1.5 CRDi AT",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1550,
    "perKmRate": 9.5,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "kia sonet",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1067",
    "year": 2024,
    "description": "Aggressive compact SUV with ventilated front seats, Bose 7-speaker audio, Level-1 ADAS, and sporty dual exhausts."
  },
  {
    "id": 68,
    "brand": "Kia",
    "model": "Seltos",
    "fullName": "Kia Seltos X-Line 1.5 Turbo DCT",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2050,
    "perKmRate": 11.5,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "kia seltos facelift",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 07 DE 1068",
    "year": 2024,
    "description": "Striking matte graphite finish, dual panoramic 10.25 inch curved displays, Level-2 ADAS, and 160PS turbo punch."
  },
  {
    "id": 69,
    "brand": "Kia",
    "model": "Carens",
    "fullName": "Kia Carens Luxury Plus 7-Seater",
    "type": "MUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 2150,
    "perKmRate": 11.5,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "kia carens",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TN 09 DE 1069",
    "year": 2024,
    "description": "Spacious 3-row recreational vehicle featuring one-touch electric tumble seats, spot reading lamps, and rear sunshades."
  },
  {
    "id": 70,
    "brand": "Kia",
    "model": "Carnival",
    "fullName": "Kia Carnival Limousine Plus",
    "type": "Luxury",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 4500,
    "perKmRate": 22,
    "driverDailyRate": 1200,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "kia carnival limousine",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 12 DE 1070",
    "year": 2025,
    "description": "Grand luxury limousine MPV with power sliding doors, dual electric sunroofs, and second row relaxation seats."
  },
  {
    "id": 71,
    "brand": "Kia",
    "model": "EV6",
    "fullName": "Kia EV6 GT-Line AWD 77.4kWh",
    "type": "Luxury",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 5500,
    "perKmRate": 22,
    "driverDailyRate": 1300,
    "image": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "kia ev6 gt line",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 01 DE 1071",
    "year": 2024,
    "description": "High-performance EV crossover: 0-100 km/h in 5.2 seconds, 708km certified range, and ultra-fast 800V charging."
  },
  {
    "id": 72,
    "brand": "MG",
    "model": "Comet EV",
    "fullName": "MG Comet EV Plush",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 4,
    "dailyRate": 1100,
    "perKmRate": 5.5,
    "driverDailyRate": 650,
    "image": "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mg comet ev",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1072",
    "year": 2024,
    "description": "Fun-sized urban electric runabout with dual floating screens, easy city turning radius and zero emissions."
  },
  {
    "id": 73,
    "brand": "MG",
    "model": "Astor",
    "fullName": "MG Astor Savvy AI 1.3 Turbo",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1650,
    "perKmRate": 10,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mg astor",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 03 DE 1073",
    "year": 2024,
    "description": "First SUV with a personal AI robot assistant on dashboard, panoramic skyroof, and Level-2 autonomous safety features."
  },
  {
    "id": 74,
    "brand": "MG",
    "model": "Hector",
    "fullName": "MG Hector Savvy Pro 1.5 Turbo CVT",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2000,
    "perKmRate": 12,
    "driverDailyRate": 850,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mg hector",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "TS 09 DE 1074",
    "year": 2024,
    "description": "India's largest 14-inch HD portrait touchscreen, infinity audio by Harman, Argyle inspired grille and panoramic roof."
  },
  {
    "id": 75,
    "brand": "MG",
    "model": "Windsor EV",
    "fullName": "MG Windsor EV Essence 38kWh",
    "type": "EV",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1950,
    "perKmRate": 7.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mg windsor ev",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 04 DE 1075",
    "year": 2024,
    "description": "Cuv crossover electric vehicle with 135-degree reclining Aero Lounge rear seats, 15.6-inch grand display and 331km range."
  },
  {
    "id": 76,
    "brand": "MG",
    "model": "Gloster",
    "fullName": "MG Gloster Savvy 4x4 Twin Turbo",
    "type": "Luxury",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 3900,
    "perKmRate": 19,
    "driverDailyRate": 1050,
    "image": "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mg gloster",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 02 DE 1076",
    "year": 2024,
    "description": "Full size 7-seater body-on-frame luxury SUV with driver massage seat, electro-mechanical differential lock and Level-1 ADAS."
  },
  {
    "id": 77,
    "brand": "Volkswagen",
    "model": "Virtus",
    "fullName": "Volkswagen Virtus GT Plus 1.5 TSI DSG",
    "type": "Sedan",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1850,
    "perKmRate": 10.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "volkswagen virtus gt",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 16 DE 1077",
    "year": 2024,
    "description": "German-engineered 5-star GNCAP sedan with 150PS EVO engine, active cylinder deactivation and razor-sharp steering."
  },
  {
    "id": 78,
    "brand": "Volkswagen",
    "model": "Taigun",
    "fullName": "Volkswagen Taigun GT Plus Edge",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1850,
    "perKmRate": 10.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "volkswagen taigun gt",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "TS 08 DE 1078",
    "year": 2024,
    "description": "High performance compact SUV with laser welded body structure, virtual cockpit, and red ambient lighting."
  },
  {
    "id": 79,
    "brand": "Volkswagen",
    "model": "Tiguan",
    "fullName": "Volkswagen Tiguan 2.0 TSI 4MOTION",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 3600,
    "perKmRate": 18,
    "driverDailyRate": 1000,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "volkswagen tiguan",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 01 DE 1079",
    "year": 2024,
    "description": "Flagship German SUV with 190PS engine, IQ.LIGHT LED matrix headlamps, panoramic sunroof and 4MOTION all-wheel-drive."
  },
  {
    "id": 80,
    "brand": "Skoda",
    "model": "Slavia",
    "fullName": "Skoda Slavia Style 1.5 TSI DSG",
    "type": "Sedan",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1800,
    "perKmRate": 10.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "skoda slavia",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 12 DE 1080",
    "year": 2024,
    "description": "Czech elegance with 521-litre luggage compartment, ventilated front leather seats, and 5-star adult & child safety rating."
  },
  {
    "id": 81,
    "brand": "Skoda",
    "model": "Kushaq",
    "fullName": "Skoda Kushaq Monte Carlo 1.5 TSI",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1850,
    "perKmRate": 10.5,
    "driverDailyRate": 800,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "skoda kushaq monte carlo",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "DL 01 DE 1081",
    "year": 2024,
    "description": "Sporty Monte Carlo edition with gloss black accents, dual-tone red cabin, digital instrument cluster and paddle shifters."
  },
  {
    "id": 82,
    "brand": "Skoda",
    "model": "Kodiaq",
    "fullName": "Skoda Kodiaq L&K 4x4 7-Seater",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 3800,
    "perKmRate": 19,
    "driverDailyRate": 1050,
    "image": "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "skoda kodiaq laurin klement",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 16 DE 1082",
    "year": 2024,
    "description": "Laurin & Klement luxury 7-seater SUV with Dynamic Chassis Control (DCC), Canton 12-speaker audio and 9 airbags."
  },
  {
    "id": 83,
    "brand": "Skoda",
    "model": "Superb",
    "fullName": "Skoda Superb L&K Luxury Sedan",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 4200,
    "perKmRate": 21,
    "driverDailyRate": 1100,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "skoda superb",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1083",
    "year": 2024,
    "description": "S-Class level rear legroom, 190PS TSI engine, electric tailgate, and tri-zone Climatronic air conditioning."
  },
  {
    "id": 84,
    "brand": "Renault",
    "model": "Kwid",
    "fullName": "Renault Kwid Climber AMT",
    "type": "Hatchback",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 900,
    "perKmRate": 7,
    "driverDailyRate": 600,
    "image": "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "renault kwid climber",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "AP 16 DE 1084",
    "year": 2023,
    "description": "SUV-inspired compact budget hatchback with 184mm clearance, roof rails, and reverse parking camera."
  },
  {
    "id": 85,
    "brand": "Renault",
    "model": "Triber",
    "fullName": "Renault Triber RXZ 7-Seater",
    "type": "MUV",
    "fuel": "Petrol",
    "transmission": "Manual",
    "seats": 7,
    "dailyRate": 1250,
    "perKmRate": 8,
    "driverDailyRate": 700,
    "image": "https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "renault triber",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "DL 02 DE 1085",
    "year": 2023,
    "description": "Ingenious sub-4m 7-seater with modular removable 3rd row seats expanding cargo space to massive 625 litres."
  },
  {
    "id": 86,
    "brand": "Renault",
    "model": "Kiger",
    "fullName": "Renault Kiger RXZ Turbo CVT",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1400,
    "perKmRate": 8.5,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "renault kiger",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 04 DE 1086",
    "year": 2024,
    "description": "4-star GNCAP sporty compact SUV with PM2.5 clean air filter, drive modes, and 205mm ground clearance."
  },
  {
    "id": 87,
    "brand": "Nissan",
    "model": "Magnite",
    "fullName": "Nissan Magnite Kuro Edition CVT",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1400,
    "perKmRate": 8.5,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "nissan magnite",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 05 DE 1087",
    "year": 2024,
    "description": "Japanese engineering with 360-degree Around View Monitor, wireless Apple CarPlay, and 100PS turbo engine."
  },
  {
    "id": 88,
    "brand": "Jeep",
    "model": "Compass",
    "fullName": "Jeep Compass Model S 4x4 Diesel AT",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 2900,
    "perKmRate": 15,
    "driverDailyRate": 950,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "jeep compass",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1088",
    "year": 2024,
    "description": "Legendary American 4x4 DNA, Selec-Terrain drive modes, dual-pane panoramic sunroof and Alpine 9-speaker audio."
  },
  {
    "id": 89,
    "brand": "Jeep",
    "model": "Meridian",
    "fullName": "Jeep Meridian Overland 4x4 7-Seater",
    "type": "SUV",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 7,
    "dailyRate": 3500,
    "perKmRate": 18,
    "driverDailyRate": 1000,
    "image": "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "jeep meridian",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 16 DE 1089",
    "year": 2024,
    "description": "True 3-row 7-seater luxury off-roader with brown leather upholstery, 360 camera, and frequency selective damping."
  },
  {
    "id": 90,
    "brand": "Jeep",
    "model": "Wrangler",
    "fullName": "Jeep Wrangler Rubicon 4x4",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 6800,
    "perKmRate": 28,
    "driverDailyRate": 1300,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "jeep wrangler rubicon",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 01 DE 1090",
    "year": 2024,
    "description": "The ultimate Trail Rated off-road machine with Tru-Lok electronic lockers, Rock-Trac 4x4, and detachable doors."
  },
  {
    "id": 91,
    "brand": "Citroen",
    "model": "Basalt",
    "fullName": "Citroen Basalt Max Turbo AT",
    "type": "SUV",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 1550,
    "perKmRate": 9.5,
    "driverDailyRate": 750,
    "image": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "citroen basalt",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 12 DE 1091",
    "year": 2025,
    "description": "French SUV coupe with magic carpet flying ride comfort, adjustable rear thigh support and 470L boot space."
  },
  {
    "id": 92,
    "brand": "BMW",
    "model": "2 Series",
    "fullName": "BMW 2 Series Gran Coupe 220i M Sport",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 5200,
    "perKmRate": 24,
    "driverDailyRate": 1200,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "bmw 2 series gran coupe",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 01 DE 1092",
    "year": 2024,
    "description": "Frameless doors, illuminated interior trims, twin turbo petrol engine, and sporty M-aerodynamics pack."
  },
  {
    "id": 93,
    "brand": "BMW",
    "model": "3 Series",
    "fullName": "BMW 3 Series Gran Limousine 330Li M Sport",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 5800,
    "perKmRate": 26,
    "driverDailyRate": 1250,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "bmw 3 series gran limousine",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1093",
    "year": 2024,
    "description": "Extended wheelbase luxury with rear comfort headrests, curved panoramic iDrive display and 258 horsepower."
  },
  {
    "id": 94,
    "brand": "BMW",
    "model": "5 Series",
    "fullName": "BMW 5 Series Long Wheelbase 530Li M Sport",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 7500,
    "perKmRate": 32,
    "driverDailyRate": 1400,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "bmw 5 series 2024",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 01 DE 1094",
    "year": 2025,
    "description": "All-new long wheelbase executive flagship with BMW Interaction Bar, Bowers & Wilkins sound, and 4-zone climate."
  },
  {
    "id": 95,
    "brand": "BMW",
    "model": "X1",
    "fullName": "BMW X1 sDrive18i M Sport",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 5500,
    "perKmRate": 25,
    "driverDailyRate": 1250,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "bmw x1 m sport",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "DL 01 DE 1095",
    "year": 2024,
    "description": "Premium compact luxury SAV with athletic road stance, curved cockpit display, and active front sport seats."
  },
  {
    "id": 96,
    "brand": "Mercedes-Benz",
    "model": "A-Class",
    "fullName": "Mercedes-Benz A-Class Limousine A200",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 5600,
    "perKmRate": 25,
    "driverDailyRate": 1250,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mercedes benz a class limousine",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "AP 16 DE 1096",
    "year": 2024,
    "description": "Entry into three-pointed star luxury: dual 10.25 inch MBUX screens, 64-colour ambient lighting and plush ride."
  },
  {
    "id": 97,
    "brand": "Mercedes-Benz",
    "model": "C-Class",
    "fullName": "Mercedes-Benz C-Class C220d",
    "type": "Luxury",
    "fuel": "Diesel",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 6800,
    "perKmRate": 30,
    "driverDailyRate": 1350,
    "image": "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mercedes benz c class",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1097",
    "year": 2024,
    "description": "Baby S-Class with 11.9-inch vertical OLED display, biometric fingerprint scanner, and 9G-TRONIC transmission."
  },
  {
    "id": 98,
    "brand": "Mercedes-Benz",
    "model": "E-Class",
    "fullName": "Mercedes-Benz New E-Class Long Wheelbase E200",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 8500,
    "perKmRate": 36,
    "driverDailyRate": 1500,
    "image": "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mercedes benz e class 2024",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "MH 01 DE 1098",
    "year": 2025,
    "description": "India's executive status benchmark: superscreen dashboard, reclining rear seats with neck warmers, and Burmester 4D audio."
  },
  {
    "id": 99,
    "brand": "Mercedes-Benz",
    "model": "GLC",
    "fullName": "Mercedes-Benz GLC 300 4MATIC",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 7800,
    "perKmRate": 34,
    "driverDailyRate": 1450,
    "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "mercedes benz glc 300",
    "availability": true,
    "condition": "Good",
    "registrationNumber": "KA 04 DE 1099",
    "year": 2024,
    "description": "Top luxury SUV featuring transparent bonnet off-road camera, DIGITAL LIGHT with projection, and 4MATIC all wheel drive."
  },
  {
    "id": 100,
    "brand": "Audi",
    "model": "A4",
    "fullName": "Audi A4 40 TFSI Technology",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 6000,
    "perKmRate": 27,
    "driverDailyRate": 1300,
    "image": "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "audi a4",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "DL 01 DE 1100",
    "year": 2024,
    "description": "Refined 2.0L turbocharged sedan with Audi Virtual Cockpit Plus, Bang & Olufsen 3D sound and acoustic glazing."
  },
  {
    "id": 101,
    "brand": "Audi",
    "model": "Q5",
    "fullName": "Audi Q5 45 TFSI Technology Quattro",
    "type": "Luxury",
    "fuel": "Petrol",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 7200,
    "perKmRate": 32,
    "driverDailyRate": 1400,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "audi q5 quattro",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "TS 09 DE 1101",
    "year": 2024,
    "description": "Quattro all-wheel drive luxury SUV with damper control, MMI touch with navigation, and panoramic glass roof."
  },
  {
    "id": 102,
    "brand": "BYD",
    "model": "Seal",
    "fullName": "BYD Seal Performance AWD Electric Sedan",
    "type": "Luxury",
    "fuel": "EV",
    "transmission": "Automatic",
    "seats": 5,
    "dailyRate": 5800,
    "perKmRate": 20,
    "driverDailyRate": 1250,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    "imageQuery": "byd seal",
    "availability": true,
    "condition": "Excellent",
    "registrationNumber": "KA 01 DE 1102",
    "year": 2024,
    "description": "0-100 in an astonishing 3.8 seconds with 530 horsepower, Blade Battery safety, rotating 15.6-inch screen, and 580km range."
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CARS_DATA };
}
